# Generated by Django 2.1.7 on 2026-03-09 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ImageApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregister',
            name='email',
        ),
    ]
